[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/tarot.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/img/*"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

